# Generated by Django 4.0.6 on 2024-12-13 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mod', models.CharField(max_length=200)),
                ('estado_mod', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricacion_veh', models.IntegerField()),
                ('precio_veh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_veh', models.CharField(max_length=50)),
                ('placa_veh', models.CharField(max_length=10)),
                ('fk_id_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prop', models.CharField(max_length=200)),
                ('apellido_prop', models.CharField(max_length=200)),
                ('email_prop', models.EmailField(max_length=200)),
                ('telefono_prop', models.CharField(max_length=12)),
                ('fk_id_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.ciudad')),
            ],
        ),
    ]
